<div data-bind="scope: 'randomReview'">
	<!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
	{
		"*": {
			"Magento_Ui/js/core/app": {
				"components": {
					"randomReview": {
						"component": "Training_JsHomework/js/review",
						"config": {
							"template": "Training_JsHomework/review/review",
							"url": <?= json_encode($block->getUrl('jshomework/review/index')) ?>
						}
					}
				}
			}
		}
	}
</script>